version: "3"

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mysql-8.0.28
    command: ["--default-authentication-plugin=mysql_native_password", "--sql_mode="]
    volumes:
      - /home/gustavo/container/mysql8/data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    networks:
      - mysql_local

networks:
  mysql_local:
    name: mysql_local

volumes:
  mysql8data: {}
